services:
  - type: web
    name: stellarminds-client
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ApiBaseUrl
        value: https://stellarmind-api.onrender.com/
